Update ncr-theme.json
Fireleaf123/plugthemes pull request #6
Opened 2016-11-12 10:16 UTC by ryu777mtg

Add emote for Neko

2016-11-12 23:04 UTC, Fuechschen requested changes
This JSON is invalid and won't be parsed. add commas and remove the comment

2016-11-12 23:35 UTC, ryu777mtg commented
All fixed sorry about that having a derp moment of forgetting after the copy paste line I would add "__comment" "Text" for the section but doubt it's needed just separated with space

2016-11-12 23:40 UTC, ryu777mtg commented
Also if you'd like it to be obfuscated I can do that as well ;)

2016-11-13 00:03 UTC, Fuechschen approved these changes

2016-12-03 02:41 UTC, merged